### ISSUE TITLE
Allow Users to Zoom in to max basemap level with warning

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/fim-js#307]
Based on discussions with Gary and our team, we should proceed allowing users to zoom in to the max level offered by their selected basemap. We should add a persistent warning (perhaps a toast notification?) once they've zoomed in further than the source material (once they've zoomed in further than the current zoom cap). The warning should refer back to the disclaimer.

Initial text for warning:
>High Zoom Level Flood extent disclaimer: You're viewing the basemap at a zoom level higher than the source material may accurately represent. Learn more about [Flood Inundation Mapping Science.](https://www.usgs.gov/mission-areas/water-resources/science/flood-inundation-mapping-science?qt-science_center_objects=0#qt-science_center_objects)

**Comment by HansVraga** [comment]
I could imagine the warning just saying "High Zoom Level disclaimer" and clicking it would show the full text and link.

**Comment by njestes** [comment]
@mitch-wim added a couple zoom levels, so handing this over to you to add some kind of warning to the user. I can add the functionality to add it or not depending on the zoom level. Or you can. Just let me know.

**Comment by mitchas** [comment]
@njestes The disclaimer is the element `.zoom-disclaimer`. Just using .show() and .hide() should work.

**Comment by njestes** [comment]
@mitch-wim commiting my changes today. when you get a chance can you take a look at the positioning of the zoom disclaimer. Right now, I think it's showing within the bounds of the map div, but it's below the USGS footer. Having the map div end at the footer could work, but if it's simpler then an offset or works too. The issue is also affected the minimized flood tools. I think they are anchoring to the bottom right of the window, so also covered partially by the USGS footer.
