### ISSUE TITLE
sliders are missing at Licking River at Catawba, KY (multi-site)

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#417]
not sure what's going on here. Also, hyperlink to NWS "catk2" is set to "NONE".

![image](https://user-images.githubusercontent.com/15948427/65908080-a5086800-e393-11e9-9202-14ce6ad9b9d2.png)

**Comment by njestes** [comment]
Missing slider issue is because of highlighted line in the attached image. It's not only hiding the colors next to the slider when no nws flood stages, but also the slider. @mitchas probably a quick fix for you. We want the slider still to show.

 
![image](https://user-images.githubusercontent.com/5325440/67817653-6c7bad00-fa6b-11e9-9ed1-c8d9e86b788e.png)
