### ISSUE TITLE
top 10 historical flood does not display, annual flood data does not show older data than 1931

### ISSUE THREAD

**Issue by mhkim01** [USGS-WiM/fim-js#545]
https://test.wim.usgs.gov/fim/?site_no=03353000

![image](https://user-images.githubusercontent.com/15948427/92650287-45f8e600-f2ba-11ea-85e0-09f1310701de.png)

![image](https://user-images.githubusercontent.com/15948427/92650377-69239580-f2ba-11ea-9ce2-95116f937a9a.png)

**Comment by mhkim01** [comment]
i see now that no GHs are associated with older streamflow data. that might cause it to not display/show older data?

**Comment by njestes** [comment]
@mhkim01 The issue seems to be that the historic flood service is returning several entries for this that don't have a gage height entered. And my sorter in the code was putting the data with no gage height (e.g. blank string) first in the array. So, for top ten it's plotting those first ten non-values, and so that chart ends up blank.

I'll have a quick fix posted soon.
